### ISSUE TITLE
How do i do Gnucash import?

### ISSUE THREAD

**Issue by valnaumov** [ccavanaugh/jgnash#15]
It is stated in changelog.adoc that I can import data from Gnucash, but I can't figure out how.

> 06/15/08 Dump GnuCash import support

**Comment by ccavanaugh** [comment]
"Dump", as in removed.  As of 2008, jGnash no longer handles Gnucash files.

**Comment by valnaumov** [comment]
Is there ERD that could help convert collected data or maybe a made script?
