### ISSUE TITLE
Balance column not resized automatically.

### ISSUE THREAD

**Issue by valnaumov** [ccavanaugh/jgnash#19]
When I insert a new slip into account, "Balance" column width is not resized accordingly. So when I enter an amount that has more positions in number than existing entries last digits are omitted (replaced with "...").  "Withdrawal" and "Balance" columns can't be resized with mouse also.
![col_resize](https://cloud.githubusercontent.com/assets/11170863/20235838/3287a20c-a8d9-11e6-990a-1fd2d8143984.png)

**Comment by ccavanaugh** [comment]
Are you using the latest 2.27.0 release when you are seeing this? 

 I fixed some font scaling and sizing issues for that release that would cause the sizing issue.  It's still possible I need to tune it a bit if you are using the 2.27.0 release.

**Comment by ccavanaugh** [comment]
Dug a bit deeper into the code and found the issue.  This will be fixed for the next release.

Thanks for reporting the issue.
