### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by numinasthmatic** [ccavanaugh/jgnash#27]
I have recently started using jgnash on OS X Sierra (or whatever tim calls it now). As yet I have only beeb setting up the chart of accounts.  Along the way, I noticed a couple of uncaught exceptions, but everything seemed to be working.

I have just tried to clear the excludedFromBudget flag on a number of accounts whose parent account had the flag set. It seems (sensibly) that when the parent is excluded, so will the children be.

This didn't work for me ( the children accounts still have the flag set as far as the exported accounts list is concerned) and a number of exceptions were generated.  The first 6 were of the same type, varying only in some particulars of the index.  The seventh was a different kettle of fish.

See attached file.
[exceptions.txt](https://github.com/ccavanaugh/jgnash/files/1101817/exceptions.txt)

**Comment by ccavanaugh** [comment]
Thanks for the detailed list and specifics.  I don't have an OSX installation to test against, but should be able to reproduce it.  It does appear to be hibernate specific and possibly a race condition of some sort.

Would you mind testing using the XML or bxds format please?

Thanks,
Craig

**Comment by ccavanaugh** [comment]
Also, are you testing against the latest release, or latest compiled from GitHub?

**Comment by numinasthmatic** [comment]
Latest release.

For the moment I will set up on a commercial product that I have (Moneyworks Cashbook) but I will test the XML and bxds formats when a get a little time.

Peter
--
Peter West
pbw@pbw.id.au
“Come to me, all who labor and are heavy laden, and I will give you rest.”

**Comment by numinasthmatic** [comment]
Release is 2.32.0.  Java is Oracle 1.8.0_131 for OS X.

> On 27 Jun 2017, at 2:18 am, Craig Cavanaugh <notifications@github.com> wrote:
> 
> Also, are you testing against the latest release, or latest compiled from GitHub?


--
Peter West
pbw@pbw.id.au
“Come to me, all who labor and are heavy laden, and I will give you rest.”

**Comment by numinasthmatic** [comment]
Craig,

In my jGnash directory I have inter alia the following files (with modification times, same day)

19:30 StJB.mv.db
10:40 StJB.mv.db.mv.db
10:06 StJB.mv.db

Does this look right?

Peter

**Comment by numinasthmatic** [comment]
No problems with bxds format.

Peter

**Comment by ccavanaugh** [comment]
StJB.mv.db is correct for H2.  File extension has changed with the latest release.  I'm looking at the issue in detail.  I do believe it's a race condition with Hibernate which is possible fixed for the next release.

**Comment by numinasthmatic** [comment]
Incidentally, this list was wrong.  The last one should be

10:06 StJB.mv.db.trace.db


> On 28 Jun 2017, at 1:50 pm, Peter West <pbw@pbw.id.au> wrote:
> 
> Craig,
> 
> In my jGnash directory I have inter alia the following files (with modification times, same day)
> 
> 19:30 StJB.mv.db
> 10:40 StJB.mv.db.mv.db
> 10:06 StJB.mv.db


--
Peter West
pbw@pbw.id.au
“Come to me, all who labor and are heavy laden, and I will give you rest.”

**Comment by ccavanaugh** [comment]
Have you tested against the latest release?
