### ISSUE TITLE
Target accounts in OFX-Import of bank statement download

### ISSUE THREAD

**Issue by Qaaqqo** [ccavanaugh/jgnash#28]
Dear Craig,

thank you for this reliable and long-term software project!

To import my bank statement download, which is only available in some custom csv format, I want to convert these csv-files to ofx-files (with a custom python script) and then import the ofx-files into jgnash. With the newest version 2.32.0 I already can import the fields Date, Payee and Amount of ofx-files. But I fail to automatically set the Account field which determines the corresponding account for each transaction. In the [OFX specification](http://ofx.net/downloads/OFX2.1.1.zip) (version 2.1.1) in chapter 11.4.3 (Statement transaction) I found the BANKACCTTO-Tag and the CCACCTTO-Tag, which seems to be a possible tag for the target account information. But jgnash seems to ignore the Tag during import.

Do you have a hint what would be the best way to automatically set the target accout for each transaction? I would like to avoid to manually set each target account for each transaction during the import process.

Thank you very much!
Daniel

**Comment by ccavanaugh** [comment]
As of right now, jGnash has the ability to learn the best account based on the memo and payee fields.

I have no issue with implementing use of the xACCTTO tags if a valid file for a unit test can be provided.

**Comment by ccavanaugh** [comment]
Daniel,

I am working on an xACCTTO tag implementation for the next release.  I should be able to commit something in the next day or two for trial.

**Comment by ccavanaugh** [comment]
I have committed code that is working well for me based on what I could find of a proper example.

**Comment by ccavanaugh** [comment]
Implemented for 2.33.1

**Comment by Qaaqqo** [comment]
Thanks for that implementation!

Sorry for the late response.

I tried version 2.33.1 with your test-ofx-file, I only changed the BANKID and the ACCTID for the first transaction to the corresponding values (Account Number and Bank ID) of one bank account in my jgnash accounts.

I can import both transactions of the test file but the proposed target accounts are not affected by the BANKACCTTO-Element in the ofx-file.

I use Linux with Oracle Java 8 and started jgnash with the shell script _jgnash_. ([terminal output](https://github.com/ccavanaugh/jgnash/files/1419416/terminal.txt))

Here you find corresponding jgnash accounts and the ofx file: [test.zip](https://github.com/ccavanaugh/jgnash/files/1419418/test.zip)

Can you reproduce the problem? Or do I have to use it in a different way?

Best wishes
Qaaqqo
