### ISSUE TITLE
2.33.1 can't open my bxds or xml file

### ISSUE THREAD

**Issue by lukebakken** [ccavanaugh/jgnash#31]
I've tried out `2.33` and `2.33.1`, but neither can open the `.bxds` file that `2.32` (and previous versions) have no trouble opening. I've tried saving the file as `.xml`, but the newer versions still won't open it. I don't see any errors in the console, either:

```
lbakken@MESSIAEN ~/Development/src/home-finances/jGnash-2.33.1 (master *%=)
$ ./jGnashFx
Sep 01, 2017 7:27:37 AM jgnash.plugin.PluginFactory getDefaultPluginDirectory
INFO: Plugin path: /Users/lbakken/Development/src/home-finances/jGnash-2.33.1/plugins/
Sep 01, 2017 7:27:37 AM jgnash.plugin.PluginFactory getUserPluginDirectory
INFO: Plugin path: /Users/lbakken/.jgnash/plugins/
Sep 01, 2017 7:27:37 AM jgnash.plugin.PluginFactory startPlugins
INFO: Starting plugin: MT940 Import
Sep 01, 2017 7:27:42 AM jgnash.uifx.views.main.MainView lambda$checkForLatestRelease$9
INFO: Version check performed
Sep 01, 2017 7:28:15 AM jgnash.plugin.PluginFactory stopPlugins
INFO: Stopping plugin: MT940 Import
```

Aha, I just tried "regular" jGnash2 instead of the FX version, and I do see errors on startup. I've attached a screenshot as well as the stack trace.

<img width="706" alt="jgnash-2 33 1-screenshot" src="https://user-images.githubusercontent.com/514926/29974455-c02c492e-8ee7-11e7-893f-66f8c3fa93ab.png">

[jgnash-2.33.1-startup.txt](https://github.com/ccavanaugh/jgnash/files/1270559/jgnash-2.33.1-startup.txt)

**Comment by ccavanaugh** [comment]
Save the file as an .h2.db in 2.32 and it should open within the latest release without issue.  There were some data related issues that impacted some xml and bxds users.

**Comment by lukebakken** [comment]
I've confirmed that this works. Should I just continue using the `.h2.db` format?

**Comment by ccavanaugh** [comment]
.h2.db format is just fine.  It's uses a bit more memory but is much more crash resistant
