### ISSUE TITLE
Problem with ampersand character "&" when importing ofx-file

### ISSUE THREAD

**Issue by Qaaqqo** [ccavanaugh/jgnash#35]
Dear ccavanaugh,

when importing an ofx-file containing an ampersand character "&" in the name field of a transaction this transaction and all other below are not imported/ proposed to import.

Here you find a corresponding test file: [bank2.ofx.zip](https://github.com/ccavanaugh/jgnash/files/1419447/bank2.ofx.zip)

I use jgnash 2.33.1 with Oracle Java 8 on Linux.

Is it a bug?

Thanks for your support!

Qaaqqo

**Comment by ccavanaugh** [comment]
The supplied file is a bit mangled in that I would expect a line break after the &.  This will cause some confusion with the SGML to XML parser.

`<NAME>To Share xx &<MEMO>Withdrawal Transfer Home Banking`

vs.

```
<NAME>To Share xx &
<MEMO>Withdrawal Transfer Home Banking
```

Is the lack of the line break actual data or a typo from hand editing a sample?  I want to make sure I'm not chasing ghosts.

Thanks!

**Comment by Qaaqqo** [comment]
The problem occurs even with a line break after the "&".

The problem does _not_ occur without the "&" but without line break before the MEMO-Tag.

Thus the problem seems to be the "&" character (or some broader parsing or encoding problem).

Best wishes

**Comment by ccavanaugh** [comment]
The soon to be released 2.33.2 version of jGnash will correctly handle the & symbol.
