### ISSUE TITLE
Please add Travis CI integration

### ISSUE THREAD

**Issue by sschuberth** [ccavanaugh/jgnash#42]
To ensure PRs pass the tests.

**Comment by ccavanaugh** [comment]
[https://travis-ci.org/ccavanaugh/jgnash](https://travis-ci.org/ccavanaugh/jgnash)

Basics for Travis are enable, but it's puking when building the Windows EXE's

Any ideas?  I can see value in this, but not if it's too intrusive.

**Comment by sschuberth** [comment]
Travis does not support Windows, only Linux and macOS. For Windows CI you'd need to use e.g. [AppVeyor](https://www.appveyor.com/).

**Comment by ccavanaugh** [comment]
The windows exe's are still a Linux based app / Gradle plugin

**Comment by ccavanaugh** [comment]
Working now.... and it did expose a unit test failure I had not found since the last release build.

The fix for building the windows EXE's was to install some lib32 dependencies.

Still learning the full capability, so open to suggestions for improvement.
