### ISSUE TITLE
Where are my investments?

### ISSUE THREAD

**Issue by mbmb65** [ccavanaugh/jgnash#45]
Show investment report

## Actual Behavior not showing ANY account!!!
![image](https://user-images.githubusercontent.com/30877047/34795493-d2a1d8c6-f652-11e7-994a-7235f77e0380.png)

## Steps to Reproduce the Problem

  1. Reports
  2. Accounts
  3. Portfolio

## Specifications

  - jGnash Version: all
  - Operating System: w10
  - Java Version

**Comment by ccavanaugh** [comment]
A portfolio report is for Investment Accounts only.  It will not show Bank / Cash / Checking accounts, etc.

If you do not have any Investment accounts, the drop down will be blank.  Ideally, the report should be disabled until an Investment Account exists.

Thanks for taking the time to report this!

**Comment by mbmb65** [comment]
How can I switch a bank account (which I created errornously!) to an investment account??

**Comment by ccavanaugh** [comment]
You can't

**Comment by mbmb65** [comment]
why??
