### ISSUE TITLE
Database path not stored correctly when skipping wizard steps (FX only)

### ISSUE THREAD

**Issue by AlexWerz** [ccavanaugh/jgnash#54]
## Expected Behavior
Database in New-Wizard should be the same I put in on forst page when skipping pages.

## Actual Behavior
Database is set to the default value.

## Steps to Reproduce the Problem
Only FX version affected, Swing works fine
  1. File - New
  2. Use default H2, change database location to "XXX" (or anything other than the default)
  3. Click next
  4. Click 5. Summary
  5. Database is still default
If you use every step in the wizard the database is correctly changed.

## Specifications

  - jGnash Version: 2.36.0
  - Operating System: Ubuntu 18.04
  - Java Version: 1.8.0_181

**Comment by ccavanaugh** [comment]
Thanks Alex!... A fix has been committed for the next release.
