### ISSUE TITLE
Problem with ampersand character "&" when importing ofx-file

### ISSUE THREAD

**Issue by fahrplaner** [ccavanaugh/jgnash#61]
Hello, it seems as if the problem #35 exists again in the jGnash-version (2.34.0, 2.35.1 and) 2.36.0 we supply new testfiles -- the files supplied in #35 works fine though.

Using java 1.8.0 and swing ui.

Cheers

[ofx.zip](https://github.com/ccavanaugh/jgnash/files/2452074/ofx.zip)

**Comment by ccavanaugh** [comment]
Looking into it.  35 addressed incorrectly OFX v2 files with incorrectly escape characters

Your files are OFX v2, and contain incorrectly escape characters.  Should be a relatively easy fix.

**Comment by fahrplaner** [comment]
OK, thanks for the hint. We'll address the problem at the source. You can close the issue or change it in something regarding error handling (XML validating?). Just in case other people run into this problem, it would be nice to have an error message, instead missing entries. Cheers.

**Comment by ccavanaugh** [comment]
A fix has been committed.  Ideally, it should be corrected upstream, but historically, multiple banks have produced non-compliant files.  It's easier to handle it gracefully instead of dealing with the noise.

Thanks for reporting and submitting the sample file.  I have included it in a unit test.
