### ISSUE TITLE
Date entry field doesn't accommodate longer date format

### ISSUE THREAD

**Issue by surratta** [ccavanaugh/jgnash#63]
## Expected Behavior

show the whole date, regardless of date format.  i.e., expand the date entry field when necessary.

## Actual Behavior

the date gets visually truncated.  the value is there, the input still works properly.

![screenshot from 2018-10-29 17-53-16](https://user-images.githubusercontent.com/1178381/47689448-5faa4c00-dbc0-11e8-9ef8-4b97ad278ec2.png)

## Steps to Reproduce the Problem

  1.  open jGnash (Fx)
  2.  in the Tools menu, change default date format to yyyy-MM-dd
  3.  try to enter a new transaction
  4.  observe that the date value of 2018-10-30 only shows up as 2018-10- (and a few of the left-most pixels of the 3)

## Specifications

  - jGnash Version:  2.36.0 Fx
  - Operating System:  Ubuntu 18.04.1 LTS
  - Java Version:  
    openjdk version "1.8.0_181"
    OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
    OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by ccavanaugh** [comment]
Thanks for reporting this.  It's now fixed for the next release.  After changing the format, you may need to restart, but after that it will then adjust for any changes in font scale.
