### ISSUE TITLE
Reconcile's Ending Balance doesn't update to match new Statement Date

### ISSUE THREAD

**Issue by cheezecat** [ccavanaugh/jgnash#68]
## Expected Behavior

When changing the Statement Date in the Reconcile Settings dialog, the Ending Balance (if not manually entered?) should be re-calculated to match the new date.

## Actual Behavior

The Ending Balance is calculated the first time the Reconcile Settings dialog is opened, and never changes after that without manual intervention.

## Steps to Reproduce the Problem

  1. Choose an account with unreconciled transactions in the previous month/period
  2. Press Reconcile button - note that Ending Balance has been correctly calculated to match default Statement Date
  3. Change Statement Date to include more or fewer transactions
  4. Notice that Ending Balance does not change

## Specifications

  - jGnash Version: 2.36.1
  - Operating System: Linux Mint 18.3
  - Java Version:

```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by kumarpranay** [comment]
This should already work. I patched this on Nov 2017 so any release after that should change the closing balance if you change the date. How are you changing the date? Can you try if this works with up/down arrows to increment/decrement the date.

**Comment by cheezecat** [comment]
Yes, this seems better now.  Thanks!
