### ISSUE TITLE
Transaction amount with comma

### ISSUE THREAD

**Issue by pchurzin** [ccavanaugh/jgnash#77]
## Expected Behavior
Edit transaction

## Actual Behavior
Can't change transaction when amount contains a comma(for example in Russian locale) 

## Steps to Reproduce the Problem

  1. Switch to the locale that uses comma as a decimal delimiter.
  2. Try to change transaction amount to the value containing comma.
  3. The Enter button remains disabled

## Specifications

  - jGnash Version: 3.0.2
  - Operating System: Ubuntu 18.04.2 LTS
  - Java Version 11.0.2

**Comment by ccavanaugh** [comment]
3.0.3 was just released with the fix.  Thanks for reporting it!!
