### ISSUE TITLE
Import QIF Not Working

### ISSUE THREAD

**Issue by henryken** [ccavanaugh/jgnash#81]
## Expected Behavior
Import QIF should open the import dialog

## Actual Behavior
Nothing happens.
Console shows:
Error: ?!Type:CCard

## Steps to Reproduce the Problem

  1. Import QIF
  2.
  3.

## Specifications

  - jGnash Version: 3.0.4
  - Operating System: Windows 10
  - Java Version: 11.0.2

**Comment by ccavanaugh** [comment]
A sample file will be required to debug.

**Comment by henryken** [comment]
Apparently this is due to the encoding format that changed. The bank now uses UTF-8 with BOM. Re-encoding it to UTF-8 works just fine.
