### ISSUE TITLE
Delete confirmation popup is miniscule

### ISSUE THREAD

**Issue by lukebakken** [ccavanaugh/jgnash#82]
## Expected Behavior

* Choose a transaction to delete
* Popup confirmation asks "Delete?" with Cancel / OK buttons

## Actual Behavior

Popup confirmation is too small to see any buttons. Hitting "Enter" for OK still works, however.

## Steps to Reproduce the Problem

  1. Choose transaction to delete
  2. Observe small popup

## Specifications

  - jGnash Version: `3.0.4`
  - Operating System: Arch Linux, up-to-date as of 2019-04-25
  - Java Version:

```
$ java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+4)
OpenJDK 64-Bit Server VM (build 11.0.3+4, mixed mode)
```

**Comment by ccavanaugh** [comment]
What desktop environment are you using?  I'm running Arch as well and I'm not seeing any issues.

Can you try without the JAVA_OPTIONS set?

**Comment by lukebakken** [comment]
I'm using KDE. Unsetting `_JAVA_OPTIONS` has no effect, unfortunately. Here's what it looks like (I have blacked out the jgnash register):

![jgnash-delete-confirmation](https://user-images.githubusercontent.com/514926/56905182-9e786c00-6a54-11e9-92ab-365cfb6b4d0a.png)

**Comment by lukebakken** [comment]
Removing prefs doesn't affect this either (`rm -rf .java/.userPrefs/jgnash/`). I use 150% text size on a 4K monitor, but adjusting that doesn't seem to have an effect.

When I was taking screenshots for this issue, the delete dialog _did_ come up correctly, once. I have no idea why, and it has since reverted to the above behavior.

**Comment by ccavanaugh** [comment]
I think I have a handle on it now. It's a 4K issue, but not having one, I've made some changes that should yield better results.

Fix will be in the next release.

**Comment by lukebakken** [comment]
Great, I'll test it out. Thanks!

**Comment by ccavanaugh** [comment]
Just to make you aware, this release will update your file.

**Comment by lukebakken** [comment]
@ccavanaugh I still see the same behavior using version `3.1.0`. Java and operating system are the same versions as when I reported this.
