### ISSUE TITLE
OpenJFX download fails on Windows 10

### ISSUE THREAD

**Issue by linocasciano** [ccavanaugh/jgnash#90]
## Expected Behavior
Start JGnash and JGnash opens with a GUI that is functional

## Actual Behavior
Start JGnash
JGnash tries to download OpenJFX libraries for Windows 10 but fails

## Steps to Reproduce the Problem

  1. Start JGnash for the first time on Windows 10
  2.  Download dialog appears for the download of OpenJFX
  3. Another dialog appears in the background stating that it cannot download the specified OpenJFX library

## Specifications

  - jGnash Version: 3.3.0
  - Operating System: Windows 10 (64bit)
  - Java Version: openjdk 11.0.5 2019-10-15
![JGnash_3 3 0_OpenJFX_lib_download_failure_2b](https://user-images.githubusercontent.com/18736049/70796097-bca39a00-1da1-11ea-9a96-0ac79e923e36.jpg)
![JGnash_3 3 0_Java_Version](https://user-images.githubusercontent.com/18736049/70796098-bca39a00-1da1-11ea-99f6-15b16d40cc3c.jpg)
![JGnash_3 3 0_OpenJFX_lib_download_failure_1a](https://user-images.githubusercontent.com/18736049/70796100-bd3c3080-1da1-11ea-830f-9b36b62698f0.jpg)
![JGnash_3 3 0_OpenJFX_lib_download_failure_1b](https://user-images.githubusercontent.com/18736049/70796102-bd3c3080-1da1-11ea-953a-5d447f65409d.jpg)
![JGnash_3 3 0_OpenJFX_lib_download_failure_2a](https://user-images.githubusercontent.com/18736049/70796103-bd3c3080-1da1-11ea-84dd-1460ec1bafc2.jpg)

**Comment by ccavanaugh** [comment]
Please try manually deleting all of the javafx*win.jar files out of the lib directory and starting jGnash again.

I suspect the download was corrupt or it could be a privilege issue seeing the Access denied warning.
Another option is to place jGnash somewhere other than "Program Files" and see if that helps.

Thanks!

**Comment by ccavanaugh** [comment]
I'm able to reproduce the problem by placing jGnash in "Program Files".  Windows is protecting itself by not allowing jGnash to download the files.  Either move jGnash to a different location such as c:\bin or run jGnash.exe as an administrator the first time so it can add the necessary files.

**Comment by lukebakken** [comment]
For what it's worth, I put jGnash in `%AppData%\jGnash` on Windows, which is guaranteed to be writable for the user who runs jGnash using that account.

**Comment by ccavanaugh** [comment]
Thanks for the tip Luke!
